"Resources"
{
	"models\astolfo_player\emotes\specialist\engineer.mdl"		"file"
	"models\astolfo_player\emotes\specialist\scout.mdl"			"file"
	"models\astolfo_player\emotes\specialist\spy.mdl"			"file"
	"models\tf2_fdd\demo.mdl"									"file"
	"models\tf2_fdd\engineer.mdl"								"file"
	"models\tf2_fdd\heavy.mdl"									"file"
	"models\tf2_fdd\medic.mdl"									"file"
	"models\tf2_fdd\pyro.mdl"									"file"
	"models\tf2_fdd\scout.mdl"									"file"
	"models\tf2_fdd\sniper.mdl"									"file"
	"models\tf2_fdd\soldier.mdl"								"file"
	"models\tf2_fdd\spy.mdl"									"file"
	"sound\goomba\stomp.wav"									"file"
	"sound\goomba\rebound.wav"									"file"
	"sound\customtaunts\specialist\specialist.mp3"				"file"
	"sound\tf2_fdd\music.wav"									"file"
}